### ISSUE TITLE
Cannot indentify uImage header in Asus FW

### ISSUE THREAD

**Issue by Crankle437** [ReFirmLabs/binwalk#380]
Hi,
binwalk (v2.1.2-fd55d7f) cannot identify uImage Header in Asus firmwares.
I've tried it with this Asus firmware: https://www.asus.com/Networking/RTAC55UHP/HelpDesk_BIOS/
Header is a typically uImage Header and 64 Bytes long: 

> 27 05 19 56

binwalk output:

```
$binwalk RT-AC55U_3.0.0.4_380_4180-ge57f472.trx  
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
64            0x40            LZMA compressed data, properties: 0x5D, dictionary size: 33554432 bytes, uncompressed size: 3936232 bytes
1356416       0x14B280        Squashfs filesystem, little endian, version 4.0, compression:xz, size: 30744259 bytes, 1602 inodes, blocksize: 131072 bytes, created: 2016-12-01 12:09:10
```

**Comment by devttys0** [comment]
Binwalk sees the uImage header, but flags it as invalid because it seems ASUS has used the `name` field of the uImage header to store some binary data (the `name` field starts with `03 00 00 04`, followed by the actual ASCII name). I guess there technically isn't any restriction on mixing binary data with ASCII data in that field, but that's not the intended use of the `name` field, which is why binwalk thinks that uImage header is a false positive. I'll have to see what the easiest way to add support for this is.

**Comment by devttys0** [comment]
Binwalk v3 seems to handle these correctly:

![image_2024-09-23_063053925](https://github.com/user-attachments/assets/07ba145c-250f-490e-9c51-7d41eeabde90)
