### ISSUE TITLE
Carve + Extract gives misleading output

### ISSUE THREAD

**Issue by bannsec** [ReFirmLabs/binwalk#473]
Not clear to me if this is the intended functionality or not. Here's the steps:

1. Create a file that contains a gzip'd something (in this case, an image)
1. Run binwalk on that file with the flags for both extracting and carving
1. Notice that the output from binwalk claims that it extracted a .png.gz file and also that it extracted a .png.
1. Check the output directory to discover that the .gz is not there, only the png

My guess is this is a byproduct of running gunzip or something on the file, which actually does the unzipping but also has the effect of removing the original file.

My view on this is, if the user asks for both carve and extract, then the files disovered from both should be there, even if one is simply gzip'd version of the other. Important, for instance, if there are comments or other forensic information relevant in the gzip.

In this example, `layer2.png.gz` is not present in the output directory.

```
+---------+------------------+---------------------------------------------------------------------------------------------------------------------+---------------+
| 0x1d4f6 | Carved | gzip compressed data, maximum compression, has original file name: "layer2.png", last modified: 2020-06-27 13:44:15 | layer2.png.gz |
| 0x1d4f6 | Extracted | gzip compressed data, maximum compression, has original file name: "layer2.png", last modified: 2020-06-27 13:44:15 | layer2.png |
| 0x1d539 | Carved | Zlib compressed data, default compression | 1D539.zlib |
| 0x1d539 | Extracted | Zlib compressed data, default compression | 1D539 |
+---------+------------------+---------------------------------------------------------------------------------------------------------------------+---------------+
```

Ref ticket that brought this to my attention: https://github.com/bannsec/stegoVeritas/issues/28

**Comment by devttys0** [comment]
The `--carve` option, when used by itself, does nothing; it is only useful when paired with the `--extract` option, so the following assumes you are running binwalk with both these options specified. 

When `--extract` is specified, you're asking binwalk to extract some data that is inside some other file. In order to do that, binwalk must do two things:

1. Carve the data of interest out of the file (in your case, this is the gzip data containing the compressed PNG image)
2. Execute some code or external utility to cover the carved data into something useful (e.g., execute the `gunzip` utility to decompress the compressed data)

When `--carve` is specified along with `--extract`, you're telling binwalk to do step 1, but NOT perform step 2: 

```-z, --carve                  Carve data from files, but don't execute extraction utilities```

So you would have only one output file, which would be the gzip file. However, this sounds like the opposite of the output that you are getting.

By default when binwalk extracts files (`--extract`) both the original carved gzip data (from step 1) and the resulting decompressed data (from step 2) would remain on disk, so you'd have two output files (in your example they should be named "layer2.png.gz" and "layer2.png" respectively).

If you've specified the `--rm` option, then after step 2 has completed, the carved file from step 1 is deleted, so you would be left with just the PNG file. This sounds to me like the output that you're getting, but that would mean that you're specifying the `--rm` option, not `--carve`.

I'm not sure what you mean by `Notice that the output from binwalk claims that it extracted a .png.gz file and also that it extracted a .png`. Binwalk's textual output is the same with or without the `--extract` and/or `--carve` options (unless you're talking about debug output?)

As a test, I took a JPG image and gzipped it. Here's what Binwalk's output looked like:

```
eve@ubuntu:/tmp$ binwalk image.jpg.gz --extract --carve

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             gzip compressed data, has original file name: "pngtree-pink-watercolor-brushes-171474-png-image_1733978.jpg", from Unix, last modified: 2020-09-17 17:39:30

eve@ubuntu:/tmp$ ls _image.jpg.gz.extracted/
pngtree-pink-watercolor-brushes-171474-png-image_1733978.jpg.gz
```
