### ISSUE TITLE
binwalk result isn't complete

### ISSUE THREAD

**Issue by ymgh96** [ReFirmLabs/binwalk#496]
I know that my [file](https://github.com/ymgh96/CTF-Writeups/blob/main/Boston%20Key%20Party%20CTF%202015/Heath%20Street/secretArchive.6303dd5dbddb15ca9c4307d0291f77f4) has multiple embedded files inside like a KGB file (bellow image confirm it and I see these files on my friend system)
![image](https://user-images.githubusercontent.com/29282323/98227331-6ff22000-1f6c-11eb-9d51-d7cfae459591.png)
binwalk output on my friend system:
![image](https://user-images.githubusercontent.com/29282323/98227543-af207100-1f6c-11eb-8199-675c7a5a9f8b.png)
But binwalk extract just one main file on my system!
![image](https://user-images.githubusercontent.com/29282323/98227698-da0ac500-1f6c-11eb-9e67-3124d1be1d32.png)
What's the problem? How do I solve it?

**Comment by devttys0** [comment]
The size of the EXT filesystem is reported to be 12582912, which is exactly the size of the secretArchive.6303dd5dbddb15ca9c4307d0291f77f4 file. My guess is the CTF creators did this on purpose, since by default binwalk tries to be smart and skip scanning the contents of the EXT filesystem and in this case it skips all the way to the end of the file.

The solution is to tell binwalk to be dumb: `binwalk --dumb secretArchive.6303dd5dbddb15ca9c4307d0291f77f4`

**Comment by ymgh96** [comment]
Thank you so much. This solution solve my problem!

> The size of the EXT filesystem is reported to be 12582912, which is exactly the size of the secretArchive.6303dd5dbddb15ca9c4307d0291f77f4 file. My guess is the CTF creators did this on purpose, since by default binwalk tries to be smart and skip scanning the contents of the EXT filesystem and in this case it skips all the way to the end of the file.
> 
> The solution is to tell binwalk to be dumb: `binwalk --dumb secretArchive.6303dd5dbddb15ca9c4307d0291f77f4`
