### ISSUE TITLE
cupx files (ie 2 zip concatenated files) are not extracted correctly

### ISSUE THREAD

**Issue by scls19fr** [ReFirmLabs/binwalk#587]
Hello,

not sure if that's a misunderstanding of how to use binwalk (I'm quite beginer in that kind of tools) but it doesn't extract cupx files correctly.

Steps to reproduce:
- Download Big_sample_file.cupx or Small_sample_file.cupx
from https://tophatsoaring.atlassian.net/browse/TH-760

- Run `binwalk --dd='.*' small_sample_file.cupx -M`

binwalk creates 4 files

```
$ tree _small_sample_file.cupx.extracted/
_small_sample_file.cupx.extracted/
├── 0
├── 1ABB2
├── 1ABC8
└── 1AD2D
```

It should in fact simply find 2 zip files (which have been simply concatenated into one).

Reference bug https://github.com/XCSoar/XCSoar/issues/795

Cupx file format description can be found at https://downloads.naviter.com/docs/SeeYou_CUPX_file_format.pdf

Foremost extracts file correctly https://github.com/XCSoar/XCSoar/issues/795#issuecomment-1008918231 but I'd prefer using binwalk as it can easily be used as Python module.

Kind regards

**Comment by devttys0** [comment]
This is likely due to binwalk identifying each ZIP entry as a separate ZIP file. Binwalk v3 is much better at preventing this type of thing, and successfully reports and extracts only the two ZIP files in the `cupx` files you linked to:

![image_2024-09-22_211857253](https://github.com/user-attachments/assets/47426b7e-b24b-4c1b-b4d8-80b2e56a5d17)
