### ISSUE TITLE
Add support for BTRFS Fillesystem

### ISSUE THREAD

**Issue by shiren00** [ReFirmLabs/binwalk#714]
We would appreciate it if anyone with additional materials or actual disk image files related to this could share them :D

- https://en.wikipedia.org/wiki/Btrfs
- https://btrfs.readthedocs.io/en/latest/dev/dev-btrfs-design.html

- extractor: https://github.com/shujianyang/btrForensics

**Comment by devttys0** [comment]
WIP: https://github.com/ReFirmLabs/binwalk/tree/btrfs_support

**Comment by devttys0** [comment]
BTRFS identification is working and merged into the master branch. Unfortunately, there doesn't seem to be an easy existing solution to extracting the files from a BTRFS image (the btrForensics tool above is interactive, not automated, and requires knowing the inode number of each file you want to extract; it also fails on BTRFS images created with default `mkfs.btrfs` settings and doesn't look like it's been updated in several years).

Since writing a custom extractor would require a good deal more time, and I'm trying to push a stable release of Binwalk this week, I'm closing this issue and I've added issue #724 to specifically write a BTRFS extractor.
